from serialization import from_indexed_sparse, s_graph_from_adj_mat, ig_to_json
import os

def main():   
    cooc_files_folder = 'hashtags\\'
    for filename in os.listdir(cooc_files_folder):
        file_path = os.path.join(cooc_files_folder, filename)
        if os.path.isfile(file_path) and filename.endswith('_coocc.npz'):#data generated by collect_hashtags.py and processed by
            # remove_indef_from_cooc_matrix.py (also non-processed versions)
            with open(file_path, 'rb') as smat_file:
                cooc_mat, index, _ = from_indexed_sparse(smat_file)
                graph = s_graph_from_adj_mat(cooc_mat, index.tolist())
                output_graph_file = file_path.replace('.npz', '_g.json')
                ig_to_json(graph, output_graph_file)
                print(f'Saved serialized graph file to "{output_graph_file}"')

if __name__ == "__main__":
    main()
    